name: Tests
on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
jobs:
  tests:
    permissions:
      contents: read
      pull-requests: write
      packages: read
    name: Tests
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          ref: ${{ github.head_ref || github.ref }}

      - name: Pull latest changes
        run: git pull origin ${{ github.head_ref || github.ref_name }}

      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: '8.4'
          extensions: mbstring, xml, ctype, json
          coverage: pcov

      - name: Install dependencies
        run: composer install --prefer-dist --no-progress --no-interaction

      - name: Run tests with coverage
        run: vendor/bin/pest --coverage --parallel

      - name: Run mutation tests
        run: vendor/bin/pest --mutate --parallel --everything --covered-only